name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Google Cloud credentials
    - name: Set up GCP Credentials
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcp-key.json
      run: echo "${{ secrets.GCP_CREDENTIALS }}" > $GOOGLE_APPLICATION_CREDENTIALS

    # Step 3: Install Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0 # Specify the Terraform version

    # Step 4: Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Step 5: Terraform Plan
    - name: Terraform Plan
      run: terraform plan

    # Step 6: Terraform Apply
    - name: Terraform Apply
      run: terraform apply -auto-approve
