name: Terraform CI/CD

on:
  push:
    branches:
      - feature/* # Matches any branch starting with "feature/"
  pull_request:
    branches:
      - main # This ensures the workflow runs for pull requests to the main branch

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Authenticate with GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
            credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Terraform Init
      - name: Terraform Init
        run: terraform -chdir=terraform init

      # Terraform Validate
      - name: Terraform Validate
        run: terraform -chdir=terraform validate

      # Terraform Format (Optional)
      - name: Terraform Format
        run: terraform -chdir=terraform fmt -check

      # Terraform Plan
      -  name: Terraform Plan
         run: terraform -chdir=terraform plan

      # Terraform Apply (Only on Pushes)
      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform -chdir=terraform apply -auto-approve -var="sample_file_name=sample_file.txt" -var="sample_file_path=/Users/mwu/Documents/ee-data-eng-bootcamp-2024/sample_files/sample_file.txt"

#      # Upload a file to GCS
#      - name: Upload a file to GCS
#        run: gsutil cp /Users/mwu/Documents/ee-data-eng-bootcamp-2024/sample_files/sample_file.txt gs://se-data-landing-monica
