name: Terraform CI/CD

on:
  push:
    branches:
      - main # Run workflows on pushes to the main branch
  pull_request:
    branches:
      - main # Optionally run on pull requests to the main branch

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6 # Replace with your Terraform version

      # Step 3: Authenticate with GCP
      - name: Authenticate to GCP
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > gcloud-key.json
          gcloud auth activate-service-account --key-file=gcloud-key.json
          gcloud config set project ${{ secrets.PROJECT_ID }}

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Format (Optional)
      - name: Terraform Format
        run: terraform fmt -check

      # Step 6: Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Step 7: Terraform Apply (Only on Pushes)
      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply
